DROP TABLE WORKSHOP;
CREATE TABLE WORKSHOP(
   Camper_ID NUMBER(4,0) NOT NULL
  ,BlockNo   NUMBER(1,0) NOT NULL
  ,Period    NUMBER(2,0) NOT NULL
  ,Activity  VARCHAR2(20) NOT NULL
);
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (21,3,1,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (21,3,2,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (21,3,3,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (21,3,4,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (21,3,5,'Arts & Crafts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (21,3,6,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (21,3,7,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (21,3,8,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (21,3,9,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (21,3,10,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (22,1,1,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (22,1,2,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (22,1,3,'Martial Arts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (22,1,4,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (22,1,5,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (22,1,6,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (22,1,7,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (22,1,8,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (22,1,9,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (22,1,10,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (23,1,1,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (23,1,2,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (23,1,3,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (23,1,4,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (23,1,5,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (23,1,6,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (23,1,7,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (23,1,8,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (23,1,9,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (23,1,10,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (39,3,1,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (39,3,2,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (39,3,3,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (39,3,4,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (39,3,5,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (39,3,6,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (39,3,7,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (39,3,8,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (39,3,9,'Dance');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (39,3,10,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (45,1,1,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (45,1,2,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (45,1,3,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (45,1,4,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (45,1,5,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (45,1,6,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (45,1,7,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (45,1,8,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (45,1,9,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (45,1,10,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (46,1,1,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (46,1,2,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (46,1,3,'Martial Arts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (46,1,4,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (46,1,5,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (46,1,6,'Dance');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (46,1,7,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (46,1,8,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (46,1,9,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (46,1,10,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (48,1,1,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (48,1,2,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (48,1,3,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (48,1,4,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (48,1,5,'Water Skiing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (48,1,6,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (48,1,7,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (48,1,8,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (48,1,9,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (48,1,10,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (59,1,1,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (59,1,2,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (59,1,3,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (59,1,4,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (59,1,5,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (59,1,6,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (59,1,7,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (59,1,8,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (59,1,9,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (59,1,10,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (60,1,1,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (60,1,2,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (60,1,3,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (60,1,4,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (60,1,5,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (60,1,6,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (60,1,7,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (60,1,8,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (60,1,9,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (60,1,10,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (64,1,1,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (64,1,2,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (64,1,3,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (64,1,4,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (64,1,5,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (64,1,6,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (64,1,7,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (64,1,8,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (64,1,9,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (64,1,10,'Martial Arts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (69,3,1,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (69,3,2,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (69,3,3,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (69,3,4,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (69,3,5,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (69,3,6,'Arts & Crafts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (69,3,7,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (69,3,8,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (69,3,9,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (69,3,10,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,1,1,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,1,2,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,1,3,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,1,4,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,1,5,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,1,6,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,1,7,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,1,8,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,1,9,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,1,10,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,3,1,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,3,2,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,3,3,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,3,4,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,3,5,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,3,6,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,3,7,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,3,8,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,3,9,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (70,3,10,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (89,1,1,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (89,1,2,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (89,1,3,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (89,1,4,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (89,1,5,'Wrestling');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (89,1,6,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (89,1,7,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (89,1,8,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (89,1,9,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (89,1,10,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,1,1,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,1,2,'Martial Arts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,1,3,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,1,4,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,1,5,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,1,6,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,1,7,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,1,8,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,1,9,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,1,10,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,3,1,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,3,2,'Martial Arts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,3,3,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,3,4,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,3,5,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,3,6,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,3,7,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,3,8,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,3,9,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (91,3,10,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,1,1,'Arts & Crafts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,1,2,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,1,3,'Martial Arts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,1,4,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,1,5,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,1,6,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,1,7,'Wrestling');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,1,8,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,1,9,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,1,10,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,2,1,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,2,2,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,2,3,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,2,4,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,2,5,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,2,6,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,2,7,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,2,8,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,2,9,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (125,2,10,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (159,1,1,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (159,1,2,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (159,1,3,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (159,1,4,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (159,1,5,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (159,1,6,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (159,1,7,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (159,1,8,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (159,1,9,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (159,1,10,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (442,3,1,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (442,3,2,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (442,3,3,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (442,3,4,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (442,3,5,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (442,3,6,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (442,3,7,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (442,3,8,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (442,3,9,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (442,3,10,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,1,1,'Dance');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,1,2,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,1,3,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,1,4,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,1,5,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,1,6,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,1,7,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,1,8,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,1,9,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,1,10,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,3,1,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,3,2,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,3,3,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,3,4,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,3,5,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,3,6,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,3,7,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,3,8,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,3,9,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (446,3,10,'Volleyball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (456,1,1,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (456,1,2,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (456,1,3,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (456,1,4,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (456,1,5,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (456,1,6,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (456,1,7,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (456,1,8,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (456,1,9,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (456,1,10,'Arts & Crafts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (489,1,1,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (489,1,2,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (489,1,3,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (489,1,4,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (489,1,5,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (489,1,6,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (489,1,7,'Water Skiing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (489,1,8,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (489,1,9,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (489,1,10,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (570,3,1,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (570,3,2,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (570,3,3,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (570,3,4,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (570,3,5,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (570,3,6,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (570,3,7,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (570,3,8,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (570,3,9,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (570,3,10,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,1,1,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,1,2,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,1,3,'Wrestling');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,1,4,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,1,5,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,1,6,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,1,7,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,1,8,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,1,9,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,1,10,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,2,1,'Arts & Crafts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,2,2,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,2,3,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,2,4,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,2,5,'Wrestling');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,2,6,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,2,7,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,2,8,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,2,9,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (637,2,10,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (657,1,1,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (657,1,2,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (657,1,3,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (657,1,4,'Water Skiing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (657,1,5,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (657,1,6,'Volleyball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (657,1,7,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (657,1,8,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (657,1,9,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (657,1,10,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (690,3,1,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (690,3,2,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (690,3,3,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (690,3,4,'Martial Arts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (690,3,5,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (690,3,6,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (690,3,7,'Volleyball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (690,3,8,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (690,3,9,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (690,3,10,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (712,3,1,'Dance');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (712,3,2,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (712,3,3,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (712,3,4,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (712,3,5,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (712,3,6,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (712,3,7,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (712,3,8,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (712,3,9,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (712,3,10,'Volleyball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (789,3,1,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (789,3,2,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (789,3,3,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (789,3,4,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (789,3,5,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (789,3,6,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (789,3,7,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (789,3,8,'Volleyball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (789,3,9,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (789,3,10,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (804,3,1,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (804,3,2,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (804,3,3,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (804,3,4,'Dance');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (804,3,5,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (804,3,6,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (804,3,7,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (804,3,8,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (804,3,9,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (804,3,10,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (817,3,1,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (817,3,2,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (817,3,3,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (817,3,4,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (817,3,5,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (817,3,6,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (817,3,7,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (817,3,8,'Water Skiing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (817,3,9,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (817,3,10,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (904,3,1,'Wrestling');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (904,3,2,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (904,3,3,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (904,3,4,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (904,3,5,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (904,3,6,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (904,3,7,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (904,3,8,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (904,3,9,'Volleyball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (904,3,10,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (948,3,1,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (948,3,2,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (948,3,3,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (948,3,4,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (948,3,5,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (948,3,6,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (948,3,7,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (948,3,8,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (948,3,9,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (948,3,10,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,2,1,'Wrestling');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,2,2,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,2,3,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,2,4,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,2,5,'Dance');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,2,6,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,2,7,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,2,8,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,2,9,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,2,10,'Water Skiing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,3,1,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,3,2,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,3,3,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,3,4,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,3,5,'Martial Arts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,3,6,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,3,7,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,3,8,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,3,9,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1067,3,10,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,1,1,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,1,2,'Dance');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,1,3,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,1,4,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,1,5,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,1,6,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,1,7,'Martial Arts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,1,8,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,1,9,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,1,10,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,2,1,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,2,2,'Wrestling');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,2,3,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,2,4,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,2,5,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,2,6,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,2,7,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,2,8,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,2,9,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,2,10,'Arts & Crafts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,3,1,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,3,2,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,3,3,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,3,4,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,3,5,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,3,6,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,3,7,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,3,8,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,3,9,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1098,3,10,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,2,1,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,2,2,'Volleyball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,2,3,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,2,4,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,2,5,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,2,6,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,2,7,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,2,8,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,2,9,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,2,10,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,3,1,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,3,2,'Water Skiing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,3,3,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,3,4,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,3,5,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,3,6,'Martial Arts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,3,7,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,3,8,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,3,9,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1212,3,10,'Dance');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1234,2,1,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1234,2,2,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1234,2,3,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1234,2,4,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1234,2,5,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1234,2,6,'Water Skiing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1234,2,7,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1234,2,8,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1234,2,9,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1234,2,10,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1254,2,1,'Dance');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1254,2,2,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1254,2,3,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1254,2,4,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1254,2,5,'Volleyball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1254,2,6,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1254,2,7,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1254,2,8,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1254,2,9,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1254,2,10,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1324,2,1,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1324,2,2,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1324,2,3,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1324,2,4,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1324,2,5,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1324,2,6,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1324,2,7,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1324,2,8,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1324,2,9,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1324,2,10,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1410,3,1,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1410,3,2,'Martial Arts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1410,3,3,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1410,3,4,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1410,3,5,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1410,3,6,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1410,3,7,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1410,3,8,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1410,3,9,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1410,3,10,'Dance');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1484,1,1,'Dance');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1484,1,2,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1484,1,3,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1484,1,4,'Dance');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1484,1,5,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1484,1,6,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1484,1,7,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1484,1,8,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1484,1,9,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (1484,1,10,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2297,1,1,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2297,1,2,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2297,1,3,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2297,1,4,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2297,1,5,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2297,1,6,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2297,1,7,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2297,1,8,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2297,1,9,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2297,1,10,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2354,2,1,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2354,2,2,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2354,2,3,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2354,2,4,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2354,2,5,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2354,2,6,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2354,2,7,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2354,2,8,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2354,2,9,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (2354,2,10,'Volleyball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3149,2,1,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3149,2,2,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3149,2,3,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3149,2,4,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3149,2,5,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3149,2,6,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3149,2,7,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3149,2,8,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3149,2,9,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3149,2,10,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,2,1,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,2,2,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,2,3,'Wrestling');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,2,4,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,2,5,'Water Skiing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,2,6,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,2,7,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,2,8,'Volleyball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,2,9,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,2,10,'Wrestling');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,3,1,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,3,2,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,3,3,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,3,4,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,3,5,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,3,6,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,3,7,'Dance');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,3,8,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,3,9,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (3699,3,10,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4033,1,1,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4033,1,2,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4033,1,3,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4033,1,4,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4033,1,5,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4033,1,6,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4033,1,7,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4033,1,8,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4033,1,9,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4033,1,10,'Water Skiing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4067,2,1,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4067,2,2,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4067,2,3,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4067,2,4,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4067,2,5,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4067,2,6,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4067,2,7,'Water Skiing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4067,2,8,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4067,2,9,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4067,2,10,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,1,1,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,1,2,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,1,3,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,1,4,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,1,5,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,1,6,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,1,7,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,1,8,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,1,9,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,1,10,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,3,1,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,3,2,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,3,3,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,3,4,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,3,5,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,3,6,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,3,7,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,3,8,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,3,9,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4483,3,10,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4569,3,1,'Volleyball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4569,3,2,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4569,3,3,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4569,3,4,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4569,3,5,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4569,3,6,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4569,3,7,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4569,3,8,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4569,3,9,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (4569,3,10,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (5510,3,1,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (5510,3,2,'Floor Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (5510,3,3,'Arts & Crafts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (5510,3,4,'Arts & Crafts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (5510,3,5,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (5510,3,6,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (5510,3,7,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (5510,3,8,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (5510,3,9,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (5510,3,10,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6014,3,1,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6014,3,2,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6014,3,3,'Wrestling');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6014,3,4,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6014,3,5,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6014,3,6,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6014,3,7,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6014,3,8,'Arts & Crafts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6014,3,9,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6014,3,10,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6125,3,1,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6125,3,2,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6125,3,3,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6125,3,4,'Martial Arts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6125,3,5,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6125,3,6,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6125,3,7,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6125,3,8,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6125,3,9,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6125,3,10,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6448,3,1,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6448,3,2,'Wrestling');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6448,3,3,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6448,3,4,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6448,3,5,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6448,3,6,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6448,3,7,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6448,3,8,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6448,3,9,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6448,3,10,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6489,1,1,'Water Skiing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6489,1,2,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6489,1,3,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6489,1,4,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6489,1,5,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6489,1,6,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6489,1,7,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6489,1,8,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6489,1,9,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6489,1,10,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,2,1,'Arts & Crafts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,2,2,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,2,3,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,2,4,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,2,5,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,2,6,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,2,7,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,2,8,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,2,9,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,2,10,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,3,1,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,3,2,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,3,3,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,3,4,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,3,5,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,3,6,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,3,7,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,3,8,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,3,9,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6589,3,10,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6606,3,1,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6606,3,2,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6606,3,3,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6606,3,4,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6606,3,5,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6606,3,6,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6606,3,7,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6606,3,8,'Water Skiing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6606,3,9,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6606,3,10,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6973,3,1,'Riflery');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6973,3,2,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6973,3,3,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6973,3,4,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6973,3,5,'Volleyball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6973,3,6,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6973,3,7,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6973,3,8,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6973,3,9,'Arts & Crafts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (6973,3,10,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7489,2,1,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7489,2,2,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7489,2,3,'Dance');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7489,2,4,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7489,2,5,'Dance');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7489,2,6,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7489,2,7,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7489,2,8,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7489,2,9,'Volleyball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7489,2,10,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7809,1,1,'Martial Arts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7809,1,2,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7809,1,3,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7809,1,4,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7809,1,5,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7809,1,6,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7809,1,7,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7809,1,8,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7809,1,9,'Arts & Crafts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7809,1,10,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7853,2,1,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7853,2,2,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7853,2,3,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7853,2,4,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7853,2,5,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7853,2,6,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7853,2,7,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7853,2,8,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7853,2,9,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7853,2,10,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7862,2,1,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7862,2,2,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7862,2,3,'Dance');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7862,2,4,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7862,2,5,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7862,2,6,'Tennis');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7862,2,7,'Martial Arts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7862,2,8,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7862,2,9,'Lifeguard Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7862,2,10,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7864,1,1,'Volleyball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7864,1,2,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7864,1,3,'Field Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7864,1,4,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7864,1,5,'Arts & Crafts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7864,1,6,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7864,1,7,'Martial Arts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7864,1,8,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7864,1,9,'Windsurfing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7864,1,10,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7968,2,1,'Ropes Course');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7968,2,2,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7968,2,3,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7968,2,4,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7968,2,5,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7968,2,6,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7968,2,7,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7968,2,8,'Sailing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7968,2,9,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (7968,2,10,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8008,3,1,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8008,3,2,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8008,3,3,'Track');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8008,3,4,'Volleyball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8008,3,5,'Skate Park Action');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8008,3,6,'Water Skiing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8008,3,7,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8008,3,8,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8008,3,9,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8008,3,10,'Mountain Biking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8908,2,1,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8908,2,2,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8908,2,3,'Football');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8908,2,4,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8908,2,5,'Kayaking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8908,2,6,'Swimming Lessons');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8908,2,7,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8908,2,8,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8908,2,9,'Weight Lifting');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8908,2,10,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8974,3,1,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8974,3,2,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8974,3,3,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8974,3,4,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8974,3,5,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8974,3,6,'Soccer');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8974,3,7,'Canoeing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8974,3,8,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8974,3,9,'Iron Man Fitness');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (8974,3,10,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9053,3,1,'Ceramics');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9053,3,2,'Martial Arts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9053,3,3,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9053,3,4,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9053,3,5,'Rugby');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9053,3,6,'In Line Hockey');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9053,3,7,'Power Boating');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9053,3,8,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9053,3,9,'Basketball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9053,3,10,'Fishing');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9080,1,1,'Baseball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9080,1,2,'Golf Clinic');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9080,1,3,'Lacrosse');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9080,1,4,'Softball');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9080,1,5,'Horseback Riding');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9080,1,6,'Nature Hiking');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9080,1,7,'Drama');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9080,1,8,'Arts & Crafts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9080,1,9,'Go Karts');
INSERT INTO WORKSHOP(Camper_ID,BlockNo,Period,Activity) VALUES (9080,1,10,'In Line Hockey');
